<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FT-DESKTOP-019" name="com.yantra.auto.yrms.scripts.RulesPage_Script" tests="42" failures="0" timestamp="11 May 2018 07:25:47 GMT" time="546.024" errors="6">
  <testcase name="testTLimits" time="13.417" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountStatusRule" time="12.713" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryHolderNameRule" time="13.373" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMFPIPRule" time="14.851" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterHolderStateRule" time="13.591" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterHolderCountryCodeRule" time="13.692" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testNavigateToAddRulePage" time="9.053" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterDOERule" time="13.140" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountTrialBalanceRule" time="12.482" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [211] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [211] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testSecondaryAccountTrialBalanceRule(RulesPage_Script.java:705)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testSecondaryAccountTrialBalanceRule -->
  <testcase name="testMasterHolderNameRule" time="13.829" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountStatusRule" time="12.780" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testReceivingCountryCodeRule" time="13.843" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountRunningBalanceRule" time="12.649" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [207] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [207] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testMasterAccountRunningBalanceRule(RulesPage_Script.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMasterAccountRunningBalanceRule -->
  <testcase name="testMasterDOBRule" time="13.502" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testProcessingCodeRule" time="13.735" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountHoldBalanceRule" time="12.645" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [209] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [209] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testMasterAccountHoldBalanceRule(RulesPage_Script.java:669)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMasterAccountHoldBalanceRule -->
  <testcase name="testSecondaryHolderCountryCodeRule" time="12.644" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountTypeRule" time="12.264" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountNumberRule" time="12.525" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryDOERule" time="13.419" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testTransactionNumberRule" time="13.273" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testTransactionCodeRule" time="13.207" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryHolderCityRule" time="12.086" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryHolderZipCodeRule" time="13.974" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountTypeRule" time="13.100" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryHolderStateRule" time="13.442" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testNavigateToRulesPage" time="7.573" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountNumberRule" time="13.509" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterHolderCityRule" time="13.334" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMFPMACRule" time="12.892" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterHolderZipCodeRule" time="13.446" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountCurrencyCodeRule" time="13.199" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountHoldBalanceRule" time="12.402" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [212] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [212] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testSecondaryAccountHoldBalanceRule(RulesPage_Script.java:723)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testSecondaryAccountHoldBalanceRule -->
  <testcase name="testSettlementTypeRule" time="12.571" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterHolderIDRule" time="13.819" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryDOBRule" time="15.706" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testDormantAccount" time="14.529" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testMasterAccountTrialBalanceRule" time="12.784" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [208] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [208] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testMasterAccountTrialBalanceRule(RulesPage_Script.java:651)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMasterAccountTrialBalanceRule -->
  <testcase name="testMasterCurrencyCodeRule" time="13.349" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testOriginCountryCodeRule" time="12.803" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
  <testcase name="testSecondaryAccountRunningBalanceRule" time="12.737" classname="com.yantra.auto.yrms.scripts.RulesPage_Script">
    <error type="java.lang.AssertionError" message="expected [210] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [210] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.yantra.auto.yrms.ui.pages.TransactionDocument.navigateToTransactionRiskReportPage(TransactionDocument.java:113)
	at com.yantra.auto.yrms.scripts.RulesPage_Script.testSecondaryAccountRunningBalanceRule(RulesPage_Script.java:687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testSecondaryAccountRunningBalanceRule -->
  <testcase name="testSecondaryHolderIDRule" time="12.142" classname="com.yantra.auto.yrms.scripts.RulesPage_Script"/>
</testsuite> <!-- com.yantra.auto.yrms.scripts.RulesPage_Script -->
